name: Download OpenLiteSpeed
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Save OpenLiteSpeed
        run: |
          docker pull --platform linux/arm64 litespeedtech/openlitespeed:latest
          docker save litespeedtech/openlitespeed:latest > litespeed_arm64.tar
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: litespeed-image
          path: litespeed_arm64.tar
