name: Download Image
on: [workflow_dispatch]
jobs:
  download:
    runs-on: ubuntu-latest
    steps:
      - name: Save Docker Image
        run: |
          docker pull --platform linux/arm64 postgres:alpine
          docker save postgres:alpine > postgres_arm64.tar
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-image
          path: postgres_arm64.tar
