name: Download MongoDB
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Save MongoDB
        run: |
          docker pull --platform linux/arm64 mongodb/mongodb-community-server:latest
          docker save mongodb/mongodb-community-server:latest > mongodb_arm64.tar
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: mongodb-image
          path: mongodb_arm64.tar
