name: Download Nginx
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Save Nginx
        run: |
          docker pull --platform linux/arm64 nginx:alpine
          docker save nginx:alpine > nginx_arm64.tar
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: nginx-image
          path: nginx_arm64.tar
