name: Download phpMyAdmin
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Save phpMyAdmin
        run: |
          docker pull --platform linux/arm64 phpmyadmin:latest
          docker save phpmyadmin:latest > phpmyadmin_arm64.tar
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: phpmyadmin-image
          path: phpmyadmin_arm64.tar
