name: Download RedisInsight
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Save RedisInsight
        run: |
          docker pull --platform linux/arm64 redis/redisinsight:latest
          docker save redis/redisinsight:latest > redisinsight_arm64.tar
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: redisinsight-image
          path: redisinsight_arm64.tar
